# Generated by Django 5.0.4 on 2025-04-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.PositiveSmallIntegerField(default=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.routine')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
