# Generated by Django 5.0.4 on 2025-04-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workoutsession_workoutexercise_workoutset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('muscle_group', models.CharField(blank=True, help_text='Primary muscle group targeted', max_length=50)),
                ('type', models.CharField(blank=True, help_text='e.g., Compound, Isolation, Isometric', max_length=50)),
                ('equipment', models.CharField(blank=True, help_text='e.g., Barbell, Dumbbell, Cable, Machine, Bodyweight', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_focus', models.CharField(choices=[('hypertrophy', 'Hypertrophy'), ('powerlifting', 'Powerlifting'), ('general_fitness', 'General Fitness'), ('injury_prevention', 'Injury Prevention'), ('all', 'All')], default='all', help_text='The user preference this rule applies to.', max_length=20)),
                ('reason', models.TextField(help_text='Scientific explanation for the suggestion.')),
                ('source', models.CharField(blank=True, help_text='Optional source for the information (e.g., study name, expert).', max_length=200)),
                ('action_type', models.CharField(choices=[('replace', 'Replace'), ('add', 'Add'), ('modify_technique', 'Modify Technique')], default='replace', max_length=20)),
                ('modification_details', models.TextField(blank=True, help_text="Specific instructions if action_type is 'add' or 'modify_technique'.")),
                ('suggested_exercise', models.ForeignKey(blank=True, help_text='The exercise recommended as a replacement or addition (null if modifying technique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_rules', to='api.predefinedexercise')),
                ('trigger_exercise', models.ForeignKey(help_text="The exercise in the user's routine that triggers this suggestion.", on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='api.predefinedexercise')),
            ],
            options={
                'ordering': ['trigger_exercise__name'],
                'unique_together': {('trigger_exercise', 'suggested_exercise', 'preference_focus', 'action_type')},
            },
        ),
    ]
