# Generated by Django 5.0.4 on 2025-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_predefinedexercise_improvementrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementrule',
            name='preference_focus',
            field=models.CharField(choices=[('hypertrophy', 'Hypertrophy'), ('powerlifting', 'Powerlifting'), ('all', 'All')], default='all', help_text='The user preference this rule applies to.', max_length=20),
        ),
    ]
