# Generated by Django 5.0.4 on 2025-05-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_improvementrule_preference_focus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutset',
            options={},
        ),
        migrations.RenameField(
            model_name='workoutset',
            old_name='exercise',
            new_name='workout_exercise',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
