# Generated by Django 5.0.4 on 2025-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workoutset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutset',
            options={'ordering': ['set_number']},
        ),
        migrations.RenameField(
            model_name='workoutset',
            old_name='workout_exercise',
            new_name='exercise',
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='set_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
