# Generated by Django 5.0.4 on 2025-05-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workoutset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='completed',
        ),
    ]
