# Generated by Django 5.0.4 on 2025-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_workoutset_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
